ALTER TABLE IF EXISTS scan_history
  ADD COLUMN IF NOT EXISTS brand TEXT,
  ADD COLUMN IF NOT EXISTS model TEXT,
  ADD COLUMN IF NOT EXISTS lowest_price_idr NUMERIC,
  ADD COLUMN IF NOT EXISTS average_price_idr NUMERIC,
  ADD COLUMN IF NOT EXISTS currency TEXT,
  ADD COLUMN IF NOT EXISTS marketplace TEXT,
  ADD COLUMN IF NOT EXISTS marketplace_url TEXT,
  ADD COLUMN IF NOT EXISTS tokopedia_url TEXT,
  ADD COLUMN IF NOT EXISTS shopee_url TEXT,
  ADD COLUMN IF NOT EXISTS confidence NUMERIC,
  ADD COLUMN IF NOT EXISTS estimate_note TEXT,
  ADD COLUMN IF NOT EXISTS is_estimate BOOLEAN NOT NULL DEFAULT TRUE;
